### ISSUE TITLE
source compliance level

### ISSUE THREAD

**Issue by anomalizer** [cgbystrom/netty-tools#2]
The maven source plugin says that the JDK compliance is 1.5 whereas the code needs 1.6.

Specifically, the @override annotation cannot be used for interface implmentations in 1.5. This problem is seen in two classes: ThriftHttpClientPipelineFactory & ThriftHttpServerPipelineFactory

**Comment by cgbystrom** [comment]
Thanks for pointing it out. Changed the requirement to 1.6 in cgbystrom/netty-tools@ace673e030f2645550b7d8e4f3f70901bf52d5a2.
