### ISSUE TITLE
Upload netty-tools to Maven Central

### ISSUE THREAD

**Issue by diwakergupta** [cgbystrom/netty-tools#6]
While it is easy to build netty-tools and deploy it locally, the barrier to using netty-tools would be even lower if it were deployed to Maven Central.

**Comment by cgbystrom** [comment]
Just opened an issue at https://issues.sonatype.org/browse/OSSRH-1862
We'll see when/if it gets accepted, then I can push to Central.

**Comment by cgbystrom** [comment]
netty-tools is now available on Maven Central. http://search.maven.org/#search%7Cga%7C1%7Cnetty-tools
